Add error handling to git service
Extheoisah/hxckr-infra pull request #4
Opened 2024-09-02 15:46 UTC by nully0x

This PR focused on adding possible errors for the git-service where possible.

2024-09-02 22:44 UTC, nully0x commented
This completes implementation for issue #2

2024-09-03 08:49 UTC, daviroo requested changes
Just some minor suggestions.

2024-09-03 08:49 UTC, daviroo commented on git-service/src/softserve/handlers.rs
> +}
The `?` operator at the end of these functions is unnecessary and incorrect. 

The functions are already returning a `Result`, so using `?` here doesn't make sense. It's trying to unwrap a `Result` that's meant to be the return value. 

Remove the `?` and the `Ok()` wrapper in the `map()` closure to fix this. The `map_err()` chain will ensure the correct `Result` type is returned.

This change will preserve the error-handling logic while correctly adhering to the function's return type.
  ```rust
  pub fn check_repo_exists(repo_name: &str) -> Result<bool, GitServiceError> {
    let command = "repo list";
    execute_command(command)
        .map(|output| {
            let repos: Vec<&str> = output.lines().collect();
            repos.iter().any(|&repo| repo.split_whitespace().any(|word| word == repo_name))
        })
        .map_err(|e| {
            error!("Failed to check repo existence: {}", e);
            GitServiceError::FailedToCheckRepoExistence(e.to_string())
        })
}

pub fn check_user_exists(username: &str) -> Result<bool, GitServiceError> {
    let command = "user list";
    execute_command(command)
        .map(|output| {
            let users: Vec<&str> = output.lines().collect();
            users.iter().any(|&user| user.split_whitespace().any(|word| word == username))
        })
        .map_err(|e| {
            error!("Failed to check user existence: {}", e);
            GitServiceError::FailedToCheckUserExistence(e.to_string())
        })
}
  ```

2024-09-03 08:49 UTC, daviroo commented on git-service/src/softserve/mod.rs
> +    let server_url = config::get_server_url();
There's a minor issue with how the config module is being referenced in the create_repo function. To ensure we're using the correct config module (the one declared as a submodule in this file), we should use the self keyword to reference it.

```suggestion
    let server_url = self::config::get_server_url();
```

2024-09-03 08:49 UTC, daviroo commented on README.md
> +### 3. Configure Nix
Very minor but we are missing a step 2 here.

2024-09-03 11:30 UTC, daviroo approved these changes

2024-09-03 13:01 UTC, Extheoisah reviewed
PR looks good. My reviews are mostly nits

2024-09-03 13:01 UTC, Extheoisah commented on README.md
This readme is specific to setting up the git service. It should live inside the git service folder. The readme in the root should be one that explains the setup of the whole infra not just a subset

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> for development, soft serve executable have been provide in the nix setup for the project you don't need to install it separately.
```suggestion
For development, a soft serve executable has been provided in the nix setup for the project so that you don't have to install it separately.
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> Before initializing Soft Serve, you need to set up the SSH key that will be used to authenticate with the server. This key should be added to the authorized keys in Soft Serve.
nit: no need to wrap this in a comment block
```suggestion
Before initializing Soft Serve, you need to set up the SSH key that will be used to authenticate with the server. This key should be added to the authorized keys in Soft Serve.
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> This will generate a new SSH key pair in the default location (`~/.ssh/id_ed25519` and `~/.ssh/id_ed25519.pub`).
nit: no need to wrap this in a comment block

```suggestion
This will generate a new SSH key pair in the default location (`~/.ssh/id_ed25519` and `~/.ssh/id_ed25519.pub`).
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> View the public key using the following command:
nit: no need to wrap this in a comment block

```suggestion
View the public key using the following command:
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> Copy the public key and add it to `SOFT_SERVE_INITIAL_ADMIN_KEYS` in your .env file.
nit: no need to wrap this in a comment block
```suggestion
Copy the public key and add it to `SOFT_SERVE_INITIAL_ADMIN_KEYS` in your .env file.
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> Next is to set config to use your private key for the server. Add the following to your `~/.ssh/config` file:
nit: no need to wrap this in a comment block
```suggestion
Next is to set config to use your private key for the server. Add the following to your `~/.ssh/config` file:
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +Initialize Soft Serve:
nit: add newline
```suggestion

Initialize Soft Serve:
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> This will start the Soft Serve server on `localhost:23231`.
nit: no need to wrap this in a comment block and add newline after sentence
```suggestion
This will start the Soft Serve server on `localhost:23231`.

```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> After initializing Soft Serve, the default DB is SQLite.
We can reword this to:
```suggestion
The default DB for soft serve is SQLite.
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +> You can change the DB to Postgres by setting the `SOFT_SERVE_POSTGRES_DB` in the `.env` file.
```suggestion
However, you can change the DB to Postgres by setting the `SOFT_SERVE_POSTGRES_DB` in the `.env` file. We use Postgres as our db for this project.
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +## Setup git-service
```suggestion
## Setup Git Service
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +In base directory of the project, run the following commands(also exports all the env variable needed for development):
nit
```suggestion
In base directory of the project, run the following commands (also ensure to have all the environment variables needed for development in the `.env` file. You can find a sample in the `.env.sample` file):
```

2024-09-03 13:01 UTC, Extheoisah commented on README.md
> +In another nix shell(you enter nix shell after running `nix develop` from the codebase base directory) cd into the `git-service` directory:
```suggestion
In another nix shell (you enter nix shell after running `nix develop` from the codebase base directory) cd into the `git-service` directory:
```

2024-09-03 13:01 UTC, Extheoisah commented on git-service/src/softserve/handlers.rs
> +        warn!("Attempt to create existing user: {}", user.username);
This log should be an error and not a warning since it returns an error
```suggestion
        error!("Attempt to create an existing user: {}", user.username);
```

2024-09-03 13:01 UTC, Extheoisah commented on git-service/src/softserve/handlers.rs
> +            repos.iter().any(|&repo| repo.trim() == repo_name)
You may want to convert the repo_name to lowercase before validation. We should do the same when saving the repo name in the database
```suggestion
            repos.iter().any(|&repo| repo.to_lowercase().trim() == repo_name.trim().to_lowercase())
```

2024-09-03 13:01 UTC, Extheoisah commented on git-service/src/softserve/handlers.rs
> +            users.iter().any(|&user| user.trim() == username)
You may want to convert the username to lowercase before validation. We should do the same when saving the username in the database
```suggestion
            users.iter().any(|&user_name| user_name.to_lowercase().trim() == username.trim().to_lowercase())
```

2024-09-03 13:01 UTC, Extheoisah commented on git-service/src/softserve/handlers.rs
> +        warn!("Attempt to create existing repo: {}", repo_req.repo_name);
This log should be an error and not a warning since it returns an error
```suggestion
        error!("Attempt to create an existing repo: {}", repo_req.repo_name);
```

2024-09-03 16:10 UTC, Extheoisah approved these changes

2024-09-03 16:11 UTC, merged